# ver: 2026-01-19
using StrojniSoucasti, Unitful, Test

@testset "dovoleneNapeti" begin
    
    A = dovoleneNapeti(250, "tah", "statický")
    @test A isa Unitful.Quantity
B = dovoleneNapeti(260u"MPa", "tah", "statický")
println("tah: ",B)
C = dovoleneNapeti(300u"MPa", "ohyb", "pulzní")
println("ohyb: ",C)
D = dovoleneNapeti(400u"MPa", "krut", "dynamický")
println("krut: ", D)
E = dovoleneNapeti(500u"MPa", "tlak", "rázový")
println("tlak: ", E)
F = dovoleneNapeti(600u"MPa", "otlačení")
println("otlaceni: ", F)
G1 = dovoleneNapeti(500u"MPa", "tah-střih", "statický-statický")
println("tah-střih: ", G1)
G2 = dovoleneNapeti(500u"MPa", "tlak-střih", "statický-statický")
println("tlak-střih: ", G2)
H1 = dovoleneNapeti(500u"MPa", "tah-střih", "statický-pulzní")
println("tah-střih: ", H1)
H2 = dovoleneNapeti(500u"MPa", "tlak-střih", "pulzní-statický")
println("tlak-střih: ", H2)
I1 = dovoleneNapeti(500u"MPa", "střih-krut", "statický-statický")
println("střih-krut: ", I1)
I2 = dovoleneNapeti(500u"MPa", "střih-krut", "pulzní-dynamický")
println("střih-krut: ", I2)
J1 = dovoleneNapeti(500u"MPa", "krut-ohyb", "dynamický-dynamický")
println("krut-ohyb: ", J1)
J2 = dovoleneNapeti(500u"MPa", "krut-ohyb", "pulzní-rázový")
println("krut-ohyb: ", J2)
K = dovoleneNapeti(350u"MPa", "střih", "dynamický")
println("střih: ", K)
L = dovoleneNapeti(450u"MPa", "ohyb", "rázový")
println("ohyb: ", L)
M = dovoleneNapeti(550u"MPa", "tlak", "pulzní")
println("tlak: ", M)
N = dovoleneNapeti(600u"MPa", "tah", "dynamický")
println("tah: ", N)
O = dovoleneNapeti(700u"MPa", "otlačení", "statický")
println("otlaceni: ", O)

end
