-- Počáteční data závitů. Nová data přidávejte další migrací.
CREATE TABLE zavit (
    id INTEGER PRIMARY KEY,
    klic TEXT NOT NULL UNIQUE,
    druh TEXT NOT NULL,
    d REAL NOT NULL CHECK (d > 0),
    p_norm REAL
);

CREATE TABLE zavit_stoupani (
    zavit_id INTEGER NOT NULL REFERENCES zavit(id),
    p REAL NOT NULL CHECK (p > 0),
    PRIMARY KEY (zavit_id, p)
);

CREATE INDEX idx_zavit_druh_d ON zavit(druh, d);

INSERT INTO zavit (klic, druh, d, p_norm) VALUES
    ('M1', 'M', 1.0, 0.25),
    ('M1.2', 'M', 1.2, 0.25),
    ('M1.4', 'M', 1.4, 0.3),
    ('M1.6', 'M', 1.6, 0.35),
    ('M1.8', 'M', 1.8, 0.35),
    ('M10', 'M', 10.0, 1.5),
    ('M12', 'M', 12.0, 1.75),
    ('M14', 'M', 14.0, 2.0),
    ('M16', 'M', 16.0, 2.0),
    ('M18', 'M', 18.0, 2.5),
    ('M2', 'M', 2.0, 0.4),
    ('M2.5', 'M', 2.5, 0.45),
    ('M20', 'M', 20.0, 2.5),
    ('M22', 'M', 22.0, 2.5),
    ('M24', 'M', 24.0, 3.0),
    ('M27', 'M', 27.0, 3.0),
    ('M3', 'M', 3.0, 0.5),
    ('M30', 'M', 30.0, 3.5),
    ('M33', 'M', 33.0, 3.5),
    ('M36', 'M', 36.0, 4.0),
    ('M39', 'M', 39.0, 4.0),
    ('M4', 'M', 4.0, 0.7),
    ('M42', 'M', 42.0, 4.5),
    ('M45', 'M', 45.0, 4.5),
    ('M48', 'M', 48.0, 5.0),
    ('M5', 'M', 5.0, 0.8),
    ('M52', 'M', 52.0, 5.0),
    ('M56', 'M', 56.0, 5.5),
    ('M6', 'M', 6.0, 1.0),
    ('M60', 'M', 60.0, 5.5),
    ('M64', 'M', 64.0, 6.0),
    ('M68', 'M', 68.0, 6.0),
    ('M8', 'M', 8.0, 1.25),
    ('Tr10x2', 'Tr', 10.0, NULL),
    ('Tr12x3', 'Tr', 12.0, NULL),
    ('Tr14x3', 'Tr', 14.0, NULL),
    ('Tr16x4', 'Tr', 16.0, NULL),
    ('Tr18x4', 'Tr', 18.0, NULL),
    ('Tr20x4', 'Tr', 20.0, NULL),
    ('Tr22x5', 'Tr', 22.0, NULL),
    ('Tr24x5', 'Tr', 24.0, NULL),
    ('Tr26x5', 'Tr', 26.0, NULL),
    ('Tr28x5', 'Tr', 28.0, NULL);

INSERT INTO zavit_stoupani (zavit_id, p) VALUES
    ((SELECT id FROM zavit WHERE klic = 'M1'), 0.2),
    ((SELECT id FROM zavit WHERE klic = 'M1'), 0.25),
    ((SELECT id FROM zavit WHERE klic = 'M1.2'), 0.2),
    ((SELECT id FROM zavit WHERE klic = 'M1.2'), 0.25),
    ((SELECT id FROM zavit WHERE klic = 'M1.4'), 0.2),
    ((SELECT id FROM zavit WHERE klic = 'M1.4'), 0.3),
    ((SELECT id FROM zavit WHERE klic = 'M1.6'), 0.2),
    ((SELECT id FROM zavit WHERE klic = 'M1.6'), 0.35),
    ((SELECT id FROM zavit WHERE klic = 'M1.8'), 0.2),
    ((SELECT id FROM zavit WHERE klic = 'M1.8'), 0.35),
    ((SELECT id FROM zavit WHERE klic = 'M10'), 0.75),
    ((SELECT id FROM zavit WHERE klic = 'M10'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M10'), 1.25),
    ((SELECT id FROM zavit WHERE klic = 'M10'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M12'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M12'), 1.25),
    ((SELECT id FROM zavit WHERE klic = 'M12'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M12'), 1.75),
    ((SELECT id FROM zavit WHERE klic = 'M14'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M14'), 1.25),
    ((SELECT id FROM zavit WHERE klic = 'M14'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M14'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M16'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M16'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M16'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M18'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M18'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M18'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M18'), 2.5),
    ((SELECT id FROM zavit WHERE klic = 'M2'), 0.25),
    ((SELECT id FROM zavit WHERE klic = 'M2'), 0.4),
    ((SELECT id FROM zavit WHERE klic = 'M2.5'), 0.35),
    ((SELECT id FROM zavit WHERE klic = 'M2.5'), 0.45),
    ((SELECT id FROM zavit WHERE klic = 'M20'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M20'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M20'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M20'), 2.5),
    ((SELECT id FROM zavit WHERE klic = 'M22'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M22'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M22'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M22'), 2.5),
    ((SELECT id FROM zavit WHERE klic = 'M24'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M24'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M24'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M24'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M27'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M27'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M27'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M3'), 0.35),
    ((SELECT id FROM zavit WHERE klic = 'M3'), 0.5),
    ((SELECT id FROM zavit WHERE klic = 'M30'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M30'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M30'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M30'), 3.5),
    ((SELECT id FROM zavit WHERE klic = 'M33'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M33'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M33'), 3.5),
    ((SELECT id FROM zavit WHERE klic = 'M36'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M36'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M36'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M36'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M39'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M39'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M39'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M39'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M4'), 0.5),
    ((SELECT id FROM zavit WHERE klic = 'M4'), 0.7),
    ((SELECT id FROM zavit WHERE klic = 'M42'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M42'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M42'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M42'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M42'), 4.5),
    ((SELECT id FROM zavit WHERE klic = 'M45'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M45'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M45'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M45'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M45'), 4.5),
    ((SELECT id FROM zavit WHERE klic = 'M48'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M48'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M48'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M48'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M48'), 5.0),
    ((SELECT id FROM zavit WHERE klic = 'M5'), 0.5),
    ((SELECT id FROM zavit WHERE klic = 'M5'), 0.8),
    ((SELECT id FROM zavit WHERE klic = 'M52'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M52'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M52'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M52'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M52'), 5.0),
    ((SELECT id FROM zavit WHERE klic = 'M56'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M56'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M56'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M56'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M56'), 5.5),
    ((SELECT id FROM zavit WHERE klic = 'M6'), 0.5),
    ((SELECT id FROM zavit WHERE klic = 'M6'), 0.75),
    ((SELECT id FROM zavit WHERE klic = 'M6'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M60'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M60'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M60'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M60'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M60'), 5.5),
    ((SELECT id FROM zavit WHERE klic = 'M64'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M64'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M64'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M64'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M64'), 6.0),
    ((SELECT id FROM zavit WHERE klic = 'M68'), 1.5),
    ((SELECT id FROM zavit WHERE klic = 'M68'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'M68'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'M68'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'M68'), 6.0),
    ((SELECT id FROM zavit WHERE klic = 'M8'), 0.75),
    ((SELECT id FROM zavit WHERE klic = 'M8'), 1.0),
    ((SELECT id FROM zavit WHERE klic = 'M8'), 1.25),
    ((SELECT id FROM zavit WHERE klic = 'Tr10x2'), 2.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr12x3'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr14x3'), 3.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr16x4'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr18x4'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr20x4'), 4.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr22x5'), 5.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr24x5'), 5.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr26x5'), 5.0),
    ((SELECT id FROM zavit WHERE klic = 'Tr28x5'), 5.0);
