schema_version = "1.0.0"

["IPE80"]
standard = "EN 10365"
h = 80.0
b = 46.0
tw = 3.8
tf = 5.2
r = 5.0
material = ["S235JR", "S355JR"]

["IPE100"]
standard = "EN 10365"
h = 100.0
b = 55.0
tw = 4.1
tf = 5.7
r = 7.0
material = ["S235JR", "S355JR"]

["IPE120"]
standard = "EN 10365"
h = 120.0
b = 64.0
tw = 4.4
tf = 6.3
r = 7.0
material = ["S235JR", "S355JR"]

["HEA100"]
standard = "EN 10365"
h = 96.0
b = 100.0
tw = 5.0
tf = 8.0
r = 12.0
material = ["S235JR", "S355JR"]

["HEB100"]
standard = "EN 10365"
h = 100.0
b = 100.0
tw = 6.0
tf = 10.0
r = 12.0
material = ["S235JR", "S355JR"]

["IPN100"]
standard = "EN 10365"
h = 100.0
b = 50.0
tw = 4.5
tf = 6.8
r = 5.0
material = ["S235JR", "S355JR"]
