schema_version = "1.0.0"
# materiály: ocel dle normy ČSN
# Kde E je první doplňková číslice (stav materiálu) a F je druhá doplňková číslice (stupeň převálcování nebo zpracování).
# 1. První doplňková číslice „E“ (Stav materiálu / Tepelné zpracování)Tato číslice definuje, v jakém stavu tepelného zpracování je hutní materiál dodáván.ČísliceVýznam 
# (Stav materiálu)
# .X0 - Tepelně nezpracovaný (původní stav po válcování za tepla)
# .1x - Normalizačně žíhaný
# .2x - Žíhaný (s blíže určeným způsobem žíhání, např. na odstranění pnutí)
# .3x - Žíhaný na měkko (časté u nástrojových ocelí pro snazší obrábění)
# .4x - Kalený nebo kalený a popuštěný při nízkých teplotách
# .5x - Normalizačně žíhaný a popuštěný
# .6x - Zušlechtěný na dolní pevnost (obvyklou u dané oceli)
# .7x - Zušlechtěný na střední pevnost
# .8x - Zušlechtěný na horní pevnost
# .9x - Stav podle zvláštního ujednání (stavy, které nelze popsat čísly 0 až 8)
# 2. Druhá doplňková číslice „F“ (Stupeň přetváření za studena)Pokud za tečkou následuje i druhá číslice, vyjadřuje nejčastěji stupeň zpevnění nebo převálcování za studena (typické pro plechy, pásy nebo dráty).ČísliceVýznam (Stupeň zpevnění)
# .x0 - Nepřeválcovaný za studena
# .x1 - Lehce převálcovaný (přemísený, k odstranění meze kluzu)
# .x2 - Čtvrttvrdý
# .x3 - Polotvrdý
# .x4 - Třičtvrtětvrdý
# .x5 - Tvrdý
# .x6 - Velmi tvrdý

[vychozi]
E = 210
G = 81
ny = 0.3
rho = 7850

["vychozi 11373"]
druh = "konstrukční ocel"
A = 7
KV = 27
T_KV = 20
svaritelnost = ""
weldable = true
thickness_max = 200

    ["11373"."11373"]
    name = "11 373"
    standard = "ČSN 41 1373"
    Re = 250
    Rm_min = 370
    Rm_max = 370
    A = 7

    ["11373"."11373.1 žíhaný"]
    name = "11 373.1 žíhaný"
    standard = "ČSN 41 1373"
    Re = 220
    Rm_min = 350
    Rm_max = 370
    A = 20

["vychozi 16440"]
druh = "konstrukční ocel"

    ["16440"."16440"]
    name = "16 440"
    standard = "ČSN"
    Re = 400
    Rm_min = 650
    Rm_max = 750
    A = 12
    KV = 35
    T_KV = 20
    svaritelnost = ""
    weldable = true
    thickness_max = 200

    ["16440"."16440 zušlechtěno"]
    name = "16 440 zušlechtěno"
    standard = "ČSN"
    Re = 700
    Rm_min = 900
    Rm_max = 1100
    A = 12
    KV = 35
    T_KV = 20
    svaritelnost = ""
    weldable = true
    thickness_max = 200
